USE GlobalHyper
GO

CREATE TABLE WORKER
(
	empID INT NOT NULL IDENTITY(1,1),
	name VARCHAR(40) NOT NULL,
	surname VARCHAR(40) NOT NULL,
	username VARCHAR(90) NOT NULL,
	iPassword VARCHAR(15) NOT NULL,
	position VARCHAR(40) DEFAULT('Cashier'),
	cashRecieved FLOAT, 
	cashTransfered FLOAT,
	loggedIn VARCHAR(10) DEFAULT('false'),
	balance FLOAT,
	PRIMARY KEY (empID)
)
GO

CREATE TABLE FINANCIALREPORT
(
	repID INT NOT NULL PRIMARY KEY IDENTITY(01, 1),
	sales FLOAT NOT NULL,
	transferTo FLOAT NOT NULL,
	recievedfrom FLOAT NOT NULL,
	repTime DATETIME NOT NULL,
	--empID INT NOT NULL FOREIGN KEY REFERENCES WORKER(empID)
)

CREATE TABLE HOURSWORKED
(
	hourID INT NOT NULL PRIMARY KEY IDENTITY(001,1),
	workHours INT NOT NULL,
	empID INT REFERENCES WORKER(empID) NOT NULL
)
GO

CREATE TABLE PRODUCTS
(
	proID INT NOT NULL PRIMARY KEY IDENTITY(100, 1),
	name VARCHAR(500) NOT NULL,
	price FLOAT NOT NULL
)
GO

CREATE TABLE CLIENT 
(
	clientID INT NOT NULL PRIMARY KEY IDENTITY(0001, 1),
	name VARCHAR(40) NOT NULL,
	lastName VARCHAR(50) NOT NULL,
	proID INT NOT NULL FOREIGN KEY REFERENCES PRODUCTS(proID)
)
GO

CREATE TABLE PRODUCTDETAILS
(
	pdID INT NOT NULL IDENTITY(00001, 1) PRIMARY KEY,
	quantity INT NOT NULL,
	proID INT NOT NULL FOREIGN KEY REFERENCES PRODUCTS(proID),
	clientID INT NOT NULL FOREIGN KEY REFERENCES CLIENT(clientID)
)
GO

CREATE TABLE AVAILABLESTOCK
(
	availID INT NOT NULL PRIMARY KEY IDENTITY(0000001, 1),
	stock INT NOT NULL,
	proID INT NOT NULL FOREIGN KEY REFERENCES PRODUCTS(proID)
)
GO